version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
            POSTGRES_DB: prisma
        ports:
            - "5433:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
